version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: lead_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ['5432:5432']

  redis:
    image: redis:6
    ports: 
      - "6379:6379"

volumes:
  postgres_data: